Add method to get elapsed time
acompany-develop/QuickMPC-libClient-py pull request #14
Opened 2022-11-02 04:06 UTC by KotaTakahashi9320

# Summary

Related to 
# Purpose

# Contents

# Testing Methods Performed

2022-11-02 10:05 UTC, arukuka requested changes

2022-11-02 10:05 UTC, arukuka commented on quickmpc/proto/libc_to_manage.proto
> +}
Please add newline at EOF if you don't mind.

2022-11-02 10:07 UTC, KotaTakahashi9320 commented on demo/unit_demo/get_elapsed_time.py
> +    print(res)
```suggestion
```

2022-11-07 06:09 UTC, KotaTakahashi9320 commented
@arukuka @come2ry @mdonaka 
諸々修正しましたので、再度ご確認お願いいたいします。

2022-11-07 06:31 UTC, mdonaka approved these changes

2022-11-08 01:34 UTC, arukuka approved these changes
Thank you!

2022-11-08 01:40 UTC, merged